using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Gomoku.Logic.BoardRelated;

namespace Gomoku.Logic.AI
{
    public class PythonMiniMax : MiniMaxBase
    {
        private const string Cmd = "D:\\Year_3_sem_2_Projects\\BachelorThesis\\Gomoku-Bachelor-Thesis\\PythonMiniMax\\main.py";
        public PythonMiniMax()
        {

        }

        protected override AnalysisResult DoAnalyze(Game clonedGame)
        {
           
            var args = new List<string>();

            var start = new ProcessStartInfo
            {
                FileName = "C:\\Python310\\python.exe",
                Arguments = $"\"{Cmd}\" \"{args}\"",
                UseShellExecute = false, // Do not use OS shell
                CreateNoWindow = true, // We don't need new window
                RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
            };
            using var process = Process.Start(start);
            using var reader = process?.StandardOutput;
            var stderr = process?.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
            var result = reader?.ReadToEnd().Split(" "); // Here is the result of StdOut(for example: print "test")
            var tile = new Tile(int.Parse(result![0]), int.Parse(result[1]), new Piece());
            return new AnalysisResult(tile);
        }
    }
}
